init:
	mkdir server;\
	mkdir client;\
	mv server.py server;\
	mv client.py client;\
	mv records.txt server;\
	touch dl_this.txt;\
	echo "download" > dl_this.txt;\
	mv dl_this.txt server;\
	touch dl_this2.txt;\
	echo "download2" > dl_this2.txt;\
	mv dl_this2.txt server;\
	touch up_this.txt;\
	echo "upload" > up_this.txt;\
	mv up_this.txt client;\
	touch up_this2.txt;\
	echo "upload2" > up_this2.txt;\
	mv up_this2.txt client;\

	
	